### ISSUE TITLE
Open Source it!

### ISSUE THREAD

**Issue by andrew** [librariesio/firehose-stream#1]
:white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square:
:white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square:
:white_large_square::white_large_square::white_large_square::white_large_square::1234::1234::white_large_square::1234::1234::white_large_square::white_large_square::white_large_square:
:white_large_square::white_large_square::white_large_square::white_large_square::1234::1234::white_large_square::1234::1234::white_large_square::white_large_square::white_large_square:
:white_large_square::white_large_square::ship::ship::ship::ship::ship::ship::ship::ship::white_large_square::white_large_square:
:white_large_square::white_large_square::ship::ship::ship::ship::ship::ship::ship::ship::white_large_square::white_large_square:
:a::a::a::a::a::a::a::a::a::a::a::a:
:white_large_square::8ball::8ball::8ball::8ball::8ball::8ball::8ball::8ball::8ball::8ball::white_large_square:
:white_large_square::white_large_square::8ball::shipit::8ball::shipit::8ball::shipit::8ball::8ball::white_large_square::white_large_square:
:white_large_square::white_large_square::white_large_square::8ball::8ball::8ball::8ball::8ball::8ball::white_large_square::white_large_square::white_large_square:
:white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square:
:white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square:

**Comment by malditogeek** [comment]
:shipit:
