### ISSUE TITLE
Please include version release date and registry pages into event object

### ISSUE THREAD

**Issue by brainoutsource** [librariesio/firehose-stream#2]
Hello!

Could you please include the version release date and registry page URL into event object?

If firehose was open-sourced I would've came up with a pull request.

Thank you!

**Comment by malditogeek** [comment]
Hi @brainoutsource, date would be easy to add. What do you mean by registry page? A link to the platform page? For example: for ExpressJS a link to https://www.npmjs.com/package/express?

**Comment by brainoutsource** [comment]
Yes, exactly! Thank you so much!

**Comment by brainoutsource** [comment]
Pretty please? :)

**Comment by andrew** [comment]
@brainoutsource I've just added this to the firehose, the responses now look like this:

<img width="1041" alt="screen shot 2015-11-07 at 8 02 04 pm" src="https://cloud.githubusercontent.com/assets/1060/11017035/8174de02-858a-11e5-9bc8-1108e85375a1.png">

Hope that helps!

**Comment by brainoutsource** [comment]
Thanks a lot!
