### ISSUE TITLE
Event name changed from `pkg` to `event`

### ISSUE THREAD

**Issue by bkeepers** [librariesio/firehose-stream#8]
It looks like on 9/21 the `event` name changed from `pkg` to `event`. Here's an example of an event from today that shows this:

```
retry: 500
event: event
data: {"platform":"Atom","name":"activate-power-mode","version":"1.0.1","package_manager_url":"https://atom.io/packages/activate-power-mode","published_at":"2016-10-05T23:35:31.244Z","project":{"name":"activate-power-mode","platform":"Atom","description":"Activate POWER MODE to write your code in style.","homepage":"","repository_url":"https://github.com/JoelBesada/activate-power-mode","normalized_licenses":["MIT"],"rank":12,"latest_release_published_at":"2016-10-05T17:35:45.485Z","latest_release_number":"1.0.0","language":"CoffeeScript","status":null,"package_manager_url":"https://atom.io/packages/activate-power-mode","stars":2948,"forks":389,"keywords":[]}}
```

Was that intentional?

**Comment by andrew** [comment]
Not intentional but I suspect it was changed a lot longer ago and not deployed for months, sorry about that!

**Comment by andrew** [comment]
@bkeepers looks like i changed it in https://github.com/librariesio/firehose/commit/3d910df7799f7627376199dbfeac7402dcd0476b back in august but failed to deploy it for months 🙈  

Will probably cause more problems for more people if I change it back now so we'll stick with event.
